### PR TITLE
[chore] integration test fixes

### PR DESCRIPTION
**Pull request by jonathanpwang**
Note: jest runs tests in parallel, which messes up nonces when sending transactions for integration tests. Use `--runInBand` to run tests sequentially:

```bash
pnpm jest --runInBand test/integration
```

### CODE REVIEW

**Comment by jonathanpwang** [comment]
@ytham I made a new folder `onchain/mock` just so I could run all tests, but the files are exactly the same except the `config.mock`. I wasn't sure what the standard way is to run tests on a function with different parameters.

**Review by ytham — APPROVED** [review]
LGTM

**Comment by ytham** [comment]
@jonathanpwang we can also potentially set MOCK as a env var and do something like this: 
https://github.com/axiom-crypto/axiom-sdk/blob/3ca2cb0244d27e2128f3b3536ddcb54607b330c8/test/integration/onchain/computeQueryStandalone.test.ts#L14
where we can run the test via 
```
MOCK=true pnpm test test/integration/onchain
```

**Comment by jonathanpwang** [comment]
> @jonathanpwang we can also potentially set MOCK as a env var and do something like this:
> 
> https://github.com/axiom-crypto/axiom-sdk/blob/3ca2cb0244d27e2128f3b3536ddcb54607b330c8/test/integration/onchain/computeQueryStandalone.test.ts#L14
> 
> 
> where we can run the test via
> ```
> MOCK=true pnpm test test/integration/onchain
> ```

Ah, I like that. Nice and clean.

**Pull request merged**
