### PR TITLE
ConfigLimitManager

### PR DESCRIPTION
**Pull request by ytham**
- ConfigLimitManager handles config limits; called from `validate`
- Adds `validate` as an option in build
- Streamlines tx/receipt getters to grab the raw tx/receipt frist and pass it into the getters to reduce the number of RPC calls

### CODE REVIEW

**Comment by ytham** [comment]
ready for review @jonathanpwang

**Review by jonathanpwang — CHANGES_REQUESTED** [review]
The determination of txSize and globalConfigSize per tx and receipt looks good. However I think there are some extra global limits to be checked: suppose you have 4 receipts that are large, but then you add a tx that is max -- then this become an invalid query since you are only allowed 1 receipt in the global max config. Similar constraint vice versa.

**Comment by ytham** [comment]
@jonathanpwang ready for re-review

**Review by jonathanpwang — APPROVED** [review]
LGTM

**Pull request merged**
